### ISSUE TITLE
可以解释一下scheduler的实现方法或者给个链接教程吗！

### ISSUE THREAD

**Issue by shaolongM17X** [Five-African/task-stage2-final-submission#1]
thx :)

**Comment by Gizeta** [comment]
scheduler的原理就是定义一个存放动画队列的数组，每次调用delay的时候如果数组为空，就直接调用相应的setTimeout，否则按顺序存入数组。每当上一个setTimeout执行完会检查数组依次取出延时执行。

为了代码简洁写了链式操作。关于链式操作可以阅读 [jQuery链式操作](http://www.cnblogs.com/justany/archive/2013/01/17/2863101.html)

另外，如果对ECMAScript新标准有兴趣，推荐使用ES6的Promise(jQuery也有实现)或结合ES7的async/await实现。

实际代码参考自http://stackoverflow.com/questions/6921275/is-it-possible-to-chain-settimeout-functions-in-javascript

**Comment by Gizeta** [comment]
已回答，关闭issue。
如果有人有疑问，下面仍可进行回复讨论。
